name: altakhfid_client
description: تطبيق التخفيض الصح — Customer storefront.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  share_plus: ^13.3.1
  app_links: ^7.2.2
  file_picker: ^13.1.0
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^22.3.1
  flutter_background_service: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/app_background.jpg
