import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'api.dart';
import 'app_state.dart';
import 'theme.dart';

String pfText(dynamic v,[String fallback=''])=>(v??fallback).toString();

class ProductSelectionSheet extends StatefulWidget{
  final Map<String,dynamic> data;
  final Future<void> Function(int,int,Map<String,dynamic>) onConfirm;
  const ProductSelectionSheet({super.key,required this.data,required this.onConfirm});
  @override State<ProductSelectionSheet> createState()=>_ProductSelectionSheetState();
}
class _ProductSelectionSheetState extends State<ProductSelectionSheet>{
  late List<Map<String,dynamic>> options;
  final selected=<String,dynamic>{};
  int? variantId;int qty=1;bool saving=false;
  @override void initState(){super.initState();options=((widget.data['options']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();
    final vs=((widget.data['variants']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();
    variantId=vs.isEmpty?null:int.tryParse(pfText(vs.first['id']));
    for(final o in options){final vals=((o['values']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();if(vals.isNotEmpty)_choose(o,vals.first,vs,false);}
  }
  void _choose(Map<String,dynamic> o,Map<String,dynamic> v,List<Map<String,dynamic>> vs,[bool notify=true]){
    final name=pfText(o['name'],'اختيار');final label=pfText(v['label']);if(label.isEmpty)return;selected[name]=label;
    final cid=v['color_id']==null?null:int.tryParse(v['color_id'].toString()),sid=v['size_id']==null?null:int.tryParse(v['size_id'].toString());
    for(final row in vs){final rc=row['color_id']==null?null:int.tryParse(row['color_id'].toString()),rs=row['size_id']==null?null:int.tryParse(row['size_id'].toString());if(cid!=null&&rc!=cid)continue;if(sid!=null&&rs!=sid)continue;variantId=int.tryParse(pfText(row['id']));break;}
    if(notify)setState((){});
  }
  Future<void>confirm()async{if(variantId==null)return;setState(()=>saving=true);try{await widget.onConfirm(variantId!,qty,Map<String,dynamic>.from(selected));if(mounted)Navigator.pop(context,true);}catch(e){if(mounted){setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(pfText(e))))}}}
  @override Widget build(BuildContext context){
    final vs=((widget.data['variants']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();
    final p=widget.data['product']is Map?Map<String,dynamic>.from(widget.data['product']):<String,dynamic>{};
    return SafeArea(child:Directionality(textDirection:TextDirection.rtl,child:Padding(padding:EdgeInsets.fromLTRB(12,10,12,MediaQuery.viewInsetsOf(context).bottom+14),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
      Center(child:Container(width:38,height:4,decoration:BoxDecoration(color:const Color(0xFFD0D0D0),borderRadius:BorderRadius.circular(8)))),
      const SizedBox(height:9),const Text('تأكيد المنتج قبل الإضافة',textAlign:TextAlign.center,style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),
      const SizedBox(height:5),Text(pfText(p['name'],'المنتج'),textAlign:TextAlign.center,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(height:11),
      ...options.map((o){final vals=((o['values']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();final cur=pfText(selected[pfText(o['name'],'اختيار')]);return Padding(padding:const EdgeInsets.only(bottom:10),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(pfText(o['name'],'اختيار'),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900)),const SizedBox(height:5),Wrap(spacing:6,runSpacing:5,children:vals.map((v)=>ChoiceChip(label:Text(pfText(v['label']),style:const TextStyle(fontSize:9)),selected:cur==pfText(v['label']),onSelected:saving?null:(_)=>_choose(o,v,vs))).toList())]));}),
      Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xFFF7F7F7),borderRadius:BorderRadius.circular(10)),child:Row(children:[const Expanded(child:Text('الكمية',style:TextStyle(fontSize:11,fontWeight:FontWeight.w900))),_q(Icons.remove,qty>1&&!saving?()=>setState(()=>qty--):null),Padding(padding:const EdgeInsets.symmetric(horizontal:14),child:Text(qty.toString(),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:14))),_q(Icons.add,!saving?()=>setState(()=>qty++):null)])),
      if(selected.isNotEmpty)Padding(padding:const EdgeInsets.only(top:7),child:Wrap(spacing:5,children:selected.entries.map((e)=>Chip(label:Text(e.key+': '+pfText(e.value),style:const TextStyle(fontSize:8.5)))).toList())),
      const SizedBox(height:10),SizedBox(height:46,child:FilledButton(onPressed:saving||variantId==null?null:confirm,style:FilledButton.styleFrom(backgroundColor:Colors.black),child:saving?const CircularProgressIndicator(color:Colors.white):const Text('تأكيد وإضافة إلى عربة التسوق',style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w900)))),
    ]))));
  }
  Widget _q(IconData i,VoidCallback?f)=>InkWell(onTap:f,child:Container(width:32,height:32,alignment:Alignment.center,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(6),border:Border.all(color:const Color(0xFFD8D8D8))),child:Icon(i,size:15)));
}

class CartShippingPromo extends StatefulWidget{
  final String subtotalSar;const CartShippingPromo({super.key,required this.subtotalSar});
  @override State<CartShippingPromo> createState()=>_CartShippingPromoState();
}
class _CartShippingPromoState extends State<CartShippingPromo>{
  Map<String,dynamic>?quote;bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void>_load()async{try{if(state.cityId==null){if(mounted)setState(()=>loading=false);return;}final d=await api.shippingQuote(cityId:state.cityId,currencyId:state.currencyId,subtotal:widget.subtotalSar);if(mounted)setState(() { quote=d['item'] is Map ? Map<String,dynamic>.from(d['item']) : null; loading=false; });}catch(_){if(mounted)setState(()=>loading=false);}}
  @override Widget build(BuildContext context){if(loading)return const SizedBox(height:40,child:Center(child:SizedBox(width:15,height:15,child:CircularProgressIndicator(strokeWidth:2))));final q=quote;if(q==null)return const SizedBox.shrink();final free=q['free']==true,rem=pfText(q['remaining_display']),adj=pfText(q['adjustment_display']);final txt=free?'🎁 الشحن مجاني على هذه السلة':rem.isNotEmpty?'أضف '+rem+' لتحصل على الشحن المجاني':adj.startsWith('-')?'🎉 خصم الشحن: '+adj:'التوصيل: '+pfText(q['price_display'],'0')+' '+pfText(q['currency_code'],state.currencyCode);return Container(margin:const EdgeInsets.fromLTRB(8,8,8,2),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:free?const Color(0xFFEAF8EF):const Color(0xFFFFF4E9),borderRadius:BorderRadius.circular(9),border:Border.all(color:free?const Color(0xFFBCE5CA):const Color(0xFFF2D5B7))),child:Row(children:[Icon(free?Icons.local_shipping:Icons.local_shipping_outlined,size:19),const SizedBox(width:7),Expanded(child:Text(txt,style:const TextStyle(fontSize:9.5,fontWeight:FontWeight.w800)))]));}
}

class CheckoutScreen extends StatefulWidget{
  final VoidCallback? onFinished;const CheckoutScreen({super.key,this.onFinished});
  @override State<CheckoutScreen> createState()=>_CheckoutScreenState();
}
class _CheckoutScreenState extends State<CheckoutScreen>{
  List<Map<String,dynamic>>addresses=[],payments=[];Map<String,dynamic>?cart;int?addressId,paymentId;bool loading=true;String note='';
  @override void initState(){super.initState();load();}
  Future<void>load()async{try{final r=await Future.wait([api.addresses(),api.paymentMethods(),api.cart(currencyId:state.currencyId)]);addresses=r[0]as List<Map<String,dynamic>>;payments=r[1]as List<Map<String,dynamic>>;final raw=r[2]as Map<String,dynamic>;cart=raw['item']is Map?Map<String,dynamic>.from(raw['item']):null;final a=addresses.firstWhere((x)=>x['is_default']==true,orElse:()=>addresses.isNotEmpty?addresses.first:<String,dynamic>{});addressId=int.tryParse(pfText(a['id']));final p=payments.firstWhere((x)=>pfText((x['settings']as Map?)?['type']).toLowerCase()=='cod',orElse:()=>payments.isNotEmpty?payments.first:<String,dynamic>{});paymentId=int.tryParse(pfText(p['id']));}catch(_){ }if(mounted)setState(()=>loading=false);}
  Future<void>review()async{if(addressId==null||paymentId==null||cart==null)return;final items=((cart!['items']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).map((x)=>{'variant_id':x['variant_id'],'qty':x['qty'],'selected_options':x['selected_options']is Map?x['selected_options']:{}}).toList();if(items.isEmpty)return;await Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderReviewScreen(cart:cart!,addresses:addresses,selectedAddress:addressId!,selectedPayment:paymentId!,payments:payments,items:items,note:note,onFinished:onFinished)));}
  @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final c=cart;if(c==null)return const Scaffold(body:Center(child:Text('تعذر تحميل السلة. اضغط إعادة المحاولة.')));final rows=((c['items']as List?)??const[]).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('التوصيل والدفع',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.fromLTRB(9,9,9,110),children:[
      const Text('١ · عنوان التوصيل',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const SizedBox(height:6),
      if(addresses.isEmpty)Container(padding:const EdgeInsets.all(12),color:Colors.white,child:const Text('أضف عنوان التوصيل من حسابي أولًا.')),
      ...addresses.map((a)=>Container(margin:const EdgeInsets.only(bottom:5),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(8),border:Border.all(color:int.tryParse(pfText(a['id']))==addressId?Colors.black:const Color(0xFFE7E7E7))),child:RadioListTile<int>(value:int.parse(pfText(a['id'])),groupValue:addressId,onChanged:(v)=>setState(()=>addressId=v),title:Row(children:[Expanded(child:Text(pfText(a['recipient_name'],'العنوان'),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))),if(a['is_default']==true)const Chip(label:Text('افتراضي',style:TextStyle(fontSize:7)))]),subtitle:Text([pfText(a['country_name']),pfText(a['region_name']),pfText(a['city_name']),pfText(a['city_area_name']),pfText(a['district']),pfText(a['street']),pfText(a['phone'])].where((x)=>x.isNotEmpty).join(' · '),style:const TextStyle(fontSize:9))))),
      const SizedBox(height:9),const Text('٢ · طريقة الدفع',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const SizedBox(height:6),
      ...payments.map((p){final s=p['settings']is Map?Map<String,dynamic>.from(p['settings']):<String,dynamic>{};final selected=int.tryParse(pfText(p['id']))==paymentId, cod=pfText(s['type']).toLowerCase()=='cod';return InkWell(onTap:()=>setState(()=>paymentId=int.tryParse(pfText(p['id']))),child:Container(margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(9),border:Border.all(color:selected?Colors.black:const Color(0xFFE5E5E5))),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
        Row(children:[Icon(cod?Icons.payments_outlined:Icons.account_balance_wallet_outlined,size:19),const SizedBox(width:7),Expanded(child:Text(pfText(p['name']),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))),if(cod)const Chip(label:Text('عند الاستلام',style:TextStyle(fontSize:7)))]),
        if(selected)...[const SizedBox(height:5),if(pfText(s['account_number']).isNotEmpty)Text('رقم الحساب: '+pfText(s['account_number']),style:const TextStyle(fontSize:9)),if(pfText(s['account_name']).isNotEmpty)Text('اسم صاحب الحساب: '+pfText(s['account_name']),style:const TextStyle(fontSize:9)),if(pfText(s['point_number']).isNotEmpty)Text('رقم النقطة/المحفظة: '+pfText(s['point_number']),style:const TextStyle(fontSize:9)),if(pfText(s['point_name']).isNotEmpty)Text('اسم النقطة: '+pfText(s['point_name']),style:const TextStyle(fontSize:9)),if(pfText(s['instructions']).isNotEmpty)Padding(padding:const EdgeInsets.only(top:3),child:Text(pfText(s['instructions']),style:const TextStyle(fontSize:9,color:ClientTheme.muted))),if(pfText(s['notes']).isNotEmpty)Padding(padding:const EdgeInsets.only(top:3),child:Text(pfText(s['notes']),style:const TextStyle(fontSize:8.5,color:ClientTheme.muted)))],
      ]));}),
      const SizedBox(height:9),const Text('٣ · ملاحظات',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const SizedBox(height:5),TextField(maxLines:3,textDirection:TextDirection.rtl,onChanged:(v)=>note=v,decoration:const InputDecoration(hintText:'ملاحظة للطلب أو المندوب')),
      const SizedBox(height:9),const Text('المنتجات',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900)),
      ...rows.map((x)=>ListTile(dense:true,contentPadding:const EdgeInsets.symmetric(horizontal:5),title:Text(pfText(x['product_name']),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800)),subtitle:Text('الكمية: '+pfText(x['qty'])+' · '+pfText(x['variant_display']),style:const TextStyle(fontSize:8)),trailing:Text(pfText(x['line_total'],'0')+' '+pfText(x['currency_code'],state.currencyCode),style:const TextStyle(fontSize:9,fontWeight:FontWeight.w900)))),
    ]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(9),child:SizedBox(height:48,child:FilledButton(onPressed:addressId!=null&&paymentId!=null?review:null,style:FilledButton.styleFrom(backgroundColor:Colors.black),child:const Text('مراجعة الطلب والتأكيد',style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w900)))))));
  }
}

class OrderReviewScreen extends StatefulWidget{
  final Map<String,dynamic> cart;final List<Map<String,dynamic>> addresses;final int selectedAddress,selectedPayment;final List<Map<String,dynamic>> payments;final List<Map<String,dynamic>> items;final String note;final VoidCallback? onFinished;
  const OrderReviewScreen({super.key,required this.cart,required this.addresses,required this.selectedAddress,required this.selectedPayment,required this.payments,required this.items,required this.note,this.onFinished});
  @override State<OrderReviewScreen> createState()=>_OrderReviewScreenState();
}
class _OrderReviewScreenState extends State<OrderReviewScreen>{
  bool busy=false,loadingQuote=true;Map<String,dynamic>?quote;
  Map<String,dynamic> get address=>widget.addresses.firstWhere((x)=>pfText(x['id'])==pfText(widget.selectedAddress));
  Map<String,dynamic> get payment=>widget.payments.firstWhere((x)=>pfText(x['id'])==pfText(widget.selectedPayment));
  @override void initState(){super.initState();loadQuote();}
  Future<void>loadQuote()async{try{final a=address;final d=await api.shippingQuote(cityId:int.tryParse(pfText(a['city_id'])),cityAreaId:int.tryParse(pfText(a['city_area_id'])),currencyId:state.currencyId,subtotal:pfText(widget.cart['subtotal_sar'],'0'));if(mounted)setState(() { quote=d['item'] is Map ? Map<String,dynamic>.from(d['item']) : null; loadingQuote=false; });}catch(_){if(mounted)setState(()=>loadingQuote=false);}}
  Future<void>confirm()async{if(busy)return;setState(()=>busy=true);try{final r=await api.createOrder(widget.selectedAddress,widget.items,paymentMethodId:widget.selectedPayment,currencyId:state.currencyId,customerNote:widget.note);final item=r['item'];final m=item is Map?Map<String,dynamic>.from(item):<String,dynamic>{};final oid=int.tryParse(pfText(m['id']));if(oid==null)throw Exception('لم يُرجع الخادم رقم الطلب.');final cod=pfText((payment['settings']as Map?)?['type']).toLowerCase()=='cod';if(cod){if(widget.onFinished!=null){Navigator.popUntil(context,(r)=>r.isFirst);widget.onFinished!();}else{Navigator.pop(context);}}else{await Navigator.push(context,MaterialPageRoute(builder:(_)=>PaymentProofScreen(orderId:oid,orderNo:pfText(m['order_no']),payment:payment,total:pfText(m['total']),currency:pfText((m['currency']as Map?)?['symbol'],state.currencySymbol))));if(mounted&&widget.onFinished!=null){Navigator.popUntil(context,(r)=>r.isFirst);widget.onFinished!();}}}catch(e){if(mounted){setState(()=>busy=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(pfText(e,'تعذر تأكيد الطلب. تحقق من العنوان والمخزون والاختيارات.'))));}}}
  @override Widget build(BuildContext context){final q=quote,sub=pfText(widget.cart['subtotal'],'0'),ship=pfText(q?['price_display'],'0'),tot=(double.tryParse(sub)??0)+(double.tryParse(ship)??0),currency=pfText(q?['currency_code'],state.currencyCode);return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('تأكيد الطلب',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(10),children:[
    _Review(title:'العنوان',icon:Icons.location_on_outlined,child:Text([pfText(address['recipient_name']),pfText(address['country_name']),pfText(address['region_name']),pfText(address['city_name']),pfText(address['city_area_name']),pfText(address['district']),pfText(address['street']),pfText(address['landmark']),pfText(address['phone'])].where((x)=>x.isNotEmpty).join('\n'),style:const TextStyle(fontSize:9.5,height:1.55))),
    _Review(title:'طريقة الدفع',icon:Icons.account_balance_wallet_outlined,child:Text(pfText(payment['name']),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900))),
    ...((widget.cart['items']as List?)??const[]).whereType<Map>().map((x)=>Container(margin:const EdgeInsets.only(bottom:5),padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(8)),child:Row(children:[SizedBox(width:55,height:68,child:pfText(x['image_url']).isEmpty?Container(color:ClientTheme.soft):Image.network(pfText(x['image_url']),fit:BoxFit.cover)),const SizedBox(width:8),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(pfText(x['product_name']),maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900)),Text(pfText(x['variant_display'),''),Text('الكمية: '+pfText(x['qty'])+' · '+pfText(x['unit_price'])+' '+pfText(x['currency_code'],state.currencyCode),style:const TextStyle(fontSize:8.5))]))]))),
    Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(9)),child:Column(children:[_p('المجموع',sub+' '+currency),_p('التوصيل',loadingQuote?'جارٍ الحساب...':q?['free']==true?'مجاني':ship+' '+currency),const Divider(height:14),_p('الإجمالي النهائي',tot.toStringAsFixed(2)+' '+currency,true)])),
    if(widget.note.trim().isNotEmpty)Padding(padding:const EdgeInsets.only(top:7),child:Text('ملاحظتك: '+widget.note,style:const TextStyle(fontSize:9,color:ClientTheme.muted))),
  ]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(9),child:SizedBox(height:50,child:FilledButton(onPressed:busy||loadingQuote?null:confirm,style:FilledButton.styleFrom(backgroundColor:Colors.black),child:busy?const CircularProgressIndicator(color:Colors.white):const Text('تأكيد وإرسال الطلب',style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w900)))))));
  }
  Widget _p(String a,String b,[bool bold=false])=>Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Row(children:[Expanded(child:Text(a,style:TextStyle(fontSize:9,fontWeight:bold?FontWeight.w900:FontWeight.w600))),Text(b,style:TextStyle(fontSize:bold?15:10,fontWeight:FontWeight.w900))]));
}
class _Review extends StatelessWidget{final String title;final IconData icon;final Widget child;const _Review({required this.title,required this.icon,required this.child});@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(9)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:18),const SizedBox(width:7),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(title,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900)),const SizedBox(height:3),child]))]));}

class PaymentProofScreen extends StatefulWidget{
  final int orderId;final String orderNo;final Map<String,dynamic> payment;final String total;final String currency;const PaymentProofScreen({super.key,required this.orderId,required this.orderNo,required this.payment,required this.total,required this.currency});
  @override State<PaymentProofScreen> createState()=>_PaymentProofScreenState();
}
class _PaymentProofScreenState extends State<PaymentProofScreen>{
  List<PlatformFile> files=[];bool busy=false;
  Future<void>pick()async{final r=await FilePicker.platform.pickFiles(allowMultiple:true,withData:true,type:FileType.custom,allowedExtensions:['jpg','jpeg','png','webp','pdf']);if(r!=null&&mounted)setState(()=>files=r.files.where((f)=>f.bytes!=null).take(3).toList());}
  Future<void>upload()async{if(files.isEmpty)return;setState(()=>busy=true);try{await api.uploadPaymentProof(widget.orderId,files);if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إرسال إثبات الدفع للمراجعة.')));Navigator.pop(context);}}catch(e){if(mounted){setState(()=>busy=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(pfText(e))));}}}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إثبات الدفع',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(12),children:[
    Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('الطلب '+widget.orderNo,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('المبلغ: '+widget.total+' '+widget.currency,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text(pfText(widget.payment['name']),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900)),..._details(widget.payment)])),
    const SizedBox(height:8),Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xFFFFF7EC),borderRadius:BorderRadius.circular(9)),child:const Text('بعد التحويل أرفق صورة أو ملف إثبات الدفع. سيبقى الدفع قيد المراجعة حتى اعتماد الإدارة.',style:TextStyle(fontSize:9.5,height:1.5))),
    const SizedBox(height:8),OutlinedButton.icon(onPressed:busy?null:pick,icon:const Icon(Icons.attach_file,size:18),label:Text(files.isEmpty?'اختيار صورة/ملف':'تم اختيار '+files.length.toString()+' ملفات',style:const TextStyle(fontSize:10))),
    if(files.isNotEmpty)Wrap(spacing:4,children:files.map((f)=>Chip(onDeleted:busy?null:()=>setState(()=>files.remove(f)),label:Text(f.name,style:const TextStyle(fontSize:7)))).toList()),
    const SizedBox(height:8),SizedBox(height:47,child:FilledButton(onPressed:busy||files.isEmpty?null:upload,style:FilledButton.styleFrom(backgroundColor:Colors.black),child:busy?const CircularProgressIndicator(color:Colors.white):const Text('إرسال إثبات الدفع',style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w900)))),
    TextButton(onPressed:()=>Navigator.pop(context),child:const Text('رفع الإثبات لاحقًا من الطلب')),
  ]));
  List<Widget> _details(Map<String,dynamic> p){final s=p['settings']is Map?Map<String,dynamic>.from(p['settings']):<String,dynamic>{};return[if(pfText(s['account_number']).isNotEmpty)Text('رقم الحساب: '+pfText(s['account_number']),style:const TextStyle(fontSize:9)),if(pfText(s['account_name']).isNotEmpty)Text('اسم صاحب الحساب: '+pfText(s['account_name']),style:const TextStyle(fontSize:9)),if(pfText(s['point_number']).isNotEmpty)Text('رقم النقطة/المحفظة: '+pfText(s['point_number']),style:const TextStyle(fontSize:9)),if(pfText(s['point_name']).isNotEmpty)Text('اسم النقطة: '+pfText(s['point_name']),style:const TextStyle(fontSize:9)),if(pfText(s['instructions']).isNotEmpty)Text(pfText(s['instructions']),style:const TextStyle(fontSize:8.5,color:ClientTheme.muted))];}
}

class OrderEditScreen extends StatefulWidget{final Map<String,dynamic> order;const OrderEditScreen({super.key,required this.order});@override State<OrderEditScreen> createState()=>_OrderEditScreenState();}
class _OrderEditScreenState extends State<OrderEditScreen>{
  late List<Map<String,dynamic>>items;List<Map<String,dynamic>>addresses=[];int?addressId;late TextEditingController note;bool busy=false;
  @override void initState(){super.initState();items=((widget.order['items']as List?)??const[]).whereType<Map>().map((e)=>{...Map<String,dynamic>.from(e),'qty':int.tryParse(pfText(e['qty']))??1}).toList();addressId=int.tryParse(pfText((widget.order['address_snapshot']as Map?)?['id']));note=TextEditingController(text:pfText(widget.order['customer_note']));load();}
  @override void dispose(){note.dispose();super.dispose();}
  Future<void>load()async{try{addresses=await api.addresses();}catch(_){}if(mounted)setState((){});}
  Future<void>save()async{setState(()=>busy=true);try{await api.updateOrder(int.tryParse(pfText(widget.order['id']))??0,{'address_id':addressId,'customer_note':note.text.trim(),'items':items.map((x)=>{'variant_id':x['variant_id'],'qty':x['qty'],'selected_options':x['selected_options']is Map?x['selected_options']:{}}).toList()});if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تحديث الطلب وإعادة حساب السعر والتوصيل.')));Navigator.pop(context,true);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(pfText(e))));}if(mounted)setState(()=>busy=false);}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('تعديل الطلب',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(10),children:[
    ...items.asMap().entries.map((x)=>Container(margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(9)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(pfText(x.value['name']),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900)),Text('السعر المحفوظ: '+pfText(x.value['sale_price_display'],'0'),style:const TextStyle(fontSize:8,color:ClientTheme.muted)),Text('الكمية: '+pfText(x.value['qty']),style:const TextStyle(fontSize:8))])),IconButton(onPressed:busy?null:()=>setState(()=>x.value['qty']=((x.value['qty']as int)>1?(x.value['qty']as int)-1:1)),icon:const Icon(Icons.remove_circle_outline,size:19)),Text(pfText(x.value['qty']),style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)),IconButton(onPressed:busy?null:()=>setState(()=>x.value['qty']=(x.value['qty']as int)+1),icon:const Icon(Icons.add_circle_outline,size:19))])),
    if(addresses.isNotEmpty)...[const Text('عنوان التوصيل',style:TextStyle(fontSize:13,fontWeight:FontWeight.w900)),...addresses.map((a)=>RadioListTile<int>(value:int.tryParse(pfText(a['id']))??0,groupValue:addressId,onChanged:(v)=>setState(()=>addressId=v),title:Text(pfText(a['recipient_name']),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800)),subtitle:Text([pfText(a['city_name']),pfText(a['city_area_name']),pfText(a['street'])].where((s)=>s.isNotEmpty).join(' · '),style:const TextStyle(fontSize:8))))],
    const SizedBox(height:5),TextField(controller:note,maxLines:3,textDirection:TextDirection.rtl,decoration:const InputDecoration(labelText:'ملاحظات الطلب')),const SizedBox(height:10),SizedBox(height:48,child:FilledButton(onPressed:busy||addressId==null?null:save,style:FilledButton.styleFrom(backgroundColor:Colors.black),child:busy?const CircularProgressIndicator(color:Colors.white):const Text('حفظ التعديل',style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w900))))
  ]));
}

class PolicyScreen extends StatefulWidget{const PolicyScreen({super.key});@override State<PolicyScreen> createState()=>_PolicyScreenState();}
class _PolicyScreenState extends State<PolicyScreen>{Map<String,dynamic>?data;bool loading=true;@override void initState(){super.initState();api.policies().then((v){if(mounted)setState(() { data=v; loading=false; });}).catchError((_){if(mounted)setState(()=>loading=false);});}@override Widget build(BuildContext context){final p=data?['privacy']is Map?Map<String,dynamic>.from(data!['privacy']):<String,dynamic>{},r=data?['return']is Map?Map<String,dynamic>.from(data!['return']):<String,dynamic>{};return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('السياسات',style:TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(10),children:[_policy(Icons.privacy_tip_outlined,pfText(p['title'],'سياسة الخصوصية'),pfText(p['body'],'لا توجد سياسة مضافة بعد.')),_policy(Icons.assignment_return_outlined,pfText(r['title'],'سياسة الإرجاع والاسترداد'),pfText(r['body'],'لا توجد سياسة مضافة بعد.'))])));}Widget _policy(IconData i,String t,String b)=>Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Icon(i,size:20),const SizedBox(width:7),Expanded(child:Text(t,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)))]),const Divider(height:18),Text(b,style:const TextStyle(fontSize:9.5,height:1.7))]));}

class SupportScreen extends StatefulWidget{const SupportScreen({super.key});@override State<SupportScreen> createState()=>_SupportScreenState();}
class _SupportScreenState extends State<SupportScreen>{
  List<Map<String,dynamic>>convs=[];int?current;List<Map<String,dynamic>>msgs=[];final input=TextEditingController();List<PlatformFile> files=[];bool sending=false;
  @override void initState(){super.initState();load();}@override void dispose(){input.dispose();super.dispose();}
  Future<void>load()async{try{convs=await api.conversations();}catch(_){}if(mounted)setState((){});}
  Future<void>openChat(int id)async{current=id;try{msgs=await api.messages(id);}catch(_){}if(mounted)setState((){});}
  Future<void>pick()async{final r=await FilePicker.platform.pickFiles(allowMultiple:true,withData:true,type:FileType.custom,allowedExtensions:['jpg','jpeg','png','webp','pdf']);if(r!=null&&mounted)setState(()=>files=r.files.where((f)=>f.bytes!=null).take(5).toList());}
  Future<void>send()async{final text=input.text.trim();if(current==null||(text.isEmpty&&files.isEmpty))return;setState(()=>sending=true);try{if(files.isEmpty)await api.sendMessage(current!,text);else await api.sendMessageWithFiles(current!,text,files);input.clear();files=[];await openChat(current!);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(pfText(e))));}if(mounted)setState(()=>sending=false);}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFFF6F6F6),appBar:AppBar(title:Text(current==null?'خدمة العملاء':'المحادثة',style:const TextStyle(fontWeight:FontWeight.w900)),actions:[if(current!=null)IconButton(onPressed:()=>setState(()=>current=null),icon:const Icon(Icons.arrow_forward))]),body:current==null?ListView(padding:const EdgeInsets.all(10),children:[
    Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.black,borderRadius:BorderRadius.circular(12)),child:const Row(children:[Icon(Icons.support_agent,color:Colors.white,size:26),SizedBox(width:8),Expanded(child:Text('تواصل معنا في الطلب والدفع والتوصيل وسنساعدك.',style:TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.w700)))])),
    const SizedBox(height:8),FilledButton.icon(onPressed:()async{final d=await api.newConversation();final raw=d['item'];final id=raw is Map?int.tryParse(pfText(raw['id'])):null;if(id!=null){await load();await openChat(id);}},icon:const Icon(Icons.add_comment_outlined),label:const Text('بدء محادثة')),
    const SizedBox(height:7),...convs.map((c)=>Container(margin:const EdgeInsets.only(bottom:6),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:ListTile(leading:CircleAvatar(child:Icon(pfText(c['order_id']).isEmpty?Icons.support_agent:Icons.shopping_bag_outlined,size:18)),title:Text(pfText(c['subject'],'خدمة العملاء'),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900)),subtitle:Text(pfText(c['status'],'مفتوحة'),style:const TextStyle(fontSize:8,color:ClientTheme.muted)),onTap:()=>openChat(int.tryParse(pfText(c['id']))??0)))),
  ]):Column(children:[
    Expanded(child:ListView.builder(padding:const EdgeInsets.all(12),itemCount:msgs.length,itemBuilder:(_,i){final m=msgs[i];final me=m['sender_type']=='customer';final at=(m['attachments']as List?)??const[];return Align(alignment:me?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(10),constraints:const BoxConstraints(maxWidth:310),decoration:BoxDecoration(color:me?Colors.black:Colors.white,borderRadius:BorderRadius.only(topLeft:const Radius.circular(14),topRight:const Radius.circular(14),bottomLeft:Radius.circular(me?14:3),bottomRight:Radius.circular(me?3:14),border:me?null:Border.all(color:const Color(0xFFE7E7E7)))),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[if(pfText(m['body']).isNotEmpty)Text(pfText(m['body']),style:TextStyle(color:me?Colors.white:Colors.black,fontSize:10,height:1.45)),if(at.isNotEmpty)...at.whereType<Map>().map((a)=>Padding(padding:const EdgeInsets.only(top:6),child:Text('📎 '+pfText(a['url']),maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:me?Colors.white70:Colors.black54,fontSize:7))))])));})),
    Container(color:Colors.white,padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Column(children:[if(files.isNotEmpty)Align(alignment:Alignment.centerRight,child:Wrap(spacing:4,children:files.map((f)=>Chip(onDeleted:sending?null:()=>setState(()=>files.remove(f)),label:Text(f.name,style:const TextStyle(fontSize:7)))).toList())),Row(children:[IconButton(onPressed:sending?null:pick,icon:const Icon(Icons.attach_file,size:19)),Expanded(child:TextField(controller:input,maxLines:3,minLines:1,textDirection:TextDirection.rtl,decoration:const InputDecoration(hintText:'اكتب رسالتك...',isDense:true))),IconButton(onPressed:sending?null:send,icon:sending?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.send_rounded,size:21))])]))
  ]));
}
